config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users
  get "up" => "rails/health#show", as: :rails_health_check

  resources :blog_posts do
    resource :cover_image, only: [:destroy], module: :blog_posts
  end

  get 'contact', to: 'home#contact'
  # get "/blog_posts/new", to: "blog_posts#new", as: :new_blog_post
  # get "/blog_posts/:id/edit", to: "blog_posts#edit", as: :edit_blog_post
  # patch "/blog_posts/:id", to: "blog_posts#update"
  # delete "/blog_posts/:id", to: "blog_posts#destroy"
  # get "/blog_posts/:id", to: "blog_posts#show", as: :blog_post
  # post "/blog_posts", to: "blog_posts#create", as: :blog_posts

  # root "blog_posts#index"
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
    has_one_attached :cover_image
    has_rich_text :content

    validates :title, presence: true
    validates :content, presence: true

    scope :sorted, -> { order(Arel.sql("published_at DESC NULLS LAST")).order(updated_at: :desc) }
    scope :draft, -> { where(published_at: nil) }
    scope :published, -> { where("published_at <= ?", Time.current) }
    scope :scheduled, -> { where("published_at > ?", Time.current) }

    def draft?
        published_at.nil?
    end

    def published?
        published_at? && published_at <= Time.current
    end

    def scheduled?
        published_at? && published_at > Time.current
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_posts/cover_images_controller.rb
class BlogPosts::CoverImagesController < ApplicationController
    include ActionView::RecordIdentifier

    before_action :authenticate_user!
    before_action :set_blog_post

    def destroy
        @blog_post.cover_image.purge_later

        respond_to do |format|
            format.html { redirect_to edit_blog_post_path(@blog_post) }
            format.turbo_stream { render turbo_stream: turbo_stream.remove(dom_id(@blog_post, :cover_image)) }
        end
    end

    private

    def set_blog_post
        @blog_post = BlogPost.find(params[:blog_post_id])
    end

end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
    before_action :set_blog_post, except: [:index, :new, :create]
    before_action :authenticate_user!, except: [:index, :show]

    def index
        @blog_posts = user_signed_in? ? BlogPost.sorted : BlogPost.published.sorted
    end

    def new
        @blog_post = BlogPost.new
    end

    def edit
    end

    def update
        if @blog_post.update(blog_post_params)
            redirect_to @blog_post
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def create
        @blog_post = BlogPost.new(blog_post_params)
        if @blog_post.save
            redirect_to @blog_post
        else
            render :new, status: :unprocessable_entity
        end
    end

    def show
    rescue ActiveRecord::RecordNotFound
        redirect_to root_path
    end

    def destroy
        @blog_post = BlogPost.find(params[:id])
        @blog_post.destroy
        redirect_to root_path
    end

    private

    def set_blog_post
        user_signed_in? ? @blog_post = BlogPost.find(params[:id]) : @blog_post = BlogPost.published.find(params[:id])
    end

    def blog_post_params
        params.require(:blog_post).permit(:title, :content, :published_at, :cover_image, :summary)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @blog_posts = user_signed_in? ? BlogPost.sorted : BlogPost.published.sorted
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/blog_posts/_form.html.erb
<%= form_with model: blog_post, local: true, class: "bg-gray-900 text-white p-8 rounded-lg shadow-lg space-y-6" do |form| %>
  <% if form.object.errors.any? %>
    <div class="bg-red-500 text-white p-4 rounded-lg">
      <% form.object.errors.full_messages.each do |message| %>
        <p><%= message %></p>
      <% end %>
    </div>
  <% end %>

  <div class="space-y-2">
    <%= form.label :title, class: "block text-sm font-medium text-gray-200" %>
    <%= form.text_field :title, class: "w-full p-2 bg-gray-800 text-white rounded-lg" %>
  </div>

  <div class="space-y-2">
    <%= form.label :cover_image, class: "block text-sm font-medium text-gray-200" %>
    <% if blog_post.cover_image.present? %>
      <div id="<%= dom_id(blog_post, :cover_image) %>" class="flex items-center space-x-4">
        <%= image_tag blog_post.cover_image, class: "w-1/3 rounded-lg" %>
        <%= link_to "Remove Cover Image", blog_post_cover_image_path(blog_post), class: "text-red-500 hover:underline", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
      </div>
    <% end %>
    <%= form.file_field :cover_image, class: "w-full p-2 bg-gray-800 text-white rounded-lg" %>
  </div>

  <div class="space-y-2">
    <%= form.label :summary, class: "block text-sm font-medium text-gray-200" %>
    <%= form.text_area :summary, class: "w-full p-2 bg-gray-800 text-white rounded-lg" %>
  </div>

  <div class="space-y-2">
    <%= form.label :content, class: "block text-sm font-medium text-gray-200" %>
    <%= form.rich_text_area :content, class: "w-full p-2 bg-gray-800 text-white rounded-lg" %>
  </div>

  <div class="space-y-2">
    <%= form.label :published_at, class: "block text-sm font-medium text-gray-200" %>
    <%= form.datetime_select :published_at, include_blank: true, class: "w-full p-2 bg-gray-800 text-white rounded-lg" %>
  </div>

  <div>
    <%= form.button 'Save', class: "w-full py-2 px-4 bg-green-500 text-white font-bold rounded-lg hover:bg-green-600" %>
  </div>
<% end %>

app/views/blog_posts/edit.html.erb
<h1>Edit Blog Post</h1>

<%= render partial: "form", locals: { blog_post: @blog_post } %>
<%= button_to "Delete", @blog_post, method: :delete, data: { turbo_confirm: "You sure?" } %>

app/views/blog_posts/index.html.erb
<h1>Here we go!</h1>
<% @blog_posts.each do |blog_post| %>
    <div>
    <% if blog_post.draft? %>
        <div class="p-2 rounded bg-gray-100 text-gray-900">Draft</div>
        <% elsif blog_post.scheduled? %>
        <div class="p-2 rounded bg-blue-100 text-gray-900">Scheduled</div>
    <% end %>
        <%= image_tag blog_post.cover_image if blog_post.cover_image.present? %>

        <h2><%= link_to blog_post.title, blog_post %></h2>
        <p><%= blog_post.content %></p>
    </div>
<% end %>

app/views/blog_posts/new.html.erb
<h1>New Blog Post</h1>

<%= render partial: "form", locals: { blog_post: @blog_post } %>

app/views/blog_posts/show.html.erb
<%= link_to "Edit", edit_blog_post_path(@blog_post) if user_signed_in? %>

<section class="relative bg-black">
  <div class="absolute inset-0 overflow-hidden z-0">
    <div class="absolute top-0 left-0 w-64 h-64 bg-gradient-to-br from-green-400 to-blue-500 opacity-50 blur-xl"></div>
    <div class="absolute top-1/2 left-1/3 w-96 h-96 bg-gradient-to-r from-yellow-400 to-red-500 opacity-50 blur-3xl"></div>
    <div class="absolute bottom-0 right-0 w-72 h-72 bg-gradient-to-tl from-purple-400 to-pink-500 opacity-50 blur-2xl"></div>
  </div>
  <div class="relative z-10 text-white pt-12 pr-0 pb-14 pl-0 bg-black bg-opacity-80">
    <div class="w-full pt-4 pr-5 pb-6 pl-5 mt-0 mr-auto mb-0 ml-auto space-y-5 sm:py-8 md:py-12 sm:space-y-8 md:space-y-16 max-w-7xl">
      <div class="flex flex-col items-center sm:px-5 md:flex-row">
        <div class="flex flex-col items-start justify-center w-full h-full pt-6 pr-0 pb-6 pl-0 mb-6 md:mb-0 md:w-1/2">
          <div class="flex flex-col items-start justify-center h-full space-y-3 transform md:pr-10 lg:pr-16 md:space-y-5">
            <h1 class="text-3xl font-bold leading-none lg:text-4xl xl:text-5xl"><%= @blog_post.title %></h1>
            <p class="text-sm text-gray-300"><%= @blog_post.published_at.strftime('%d %b %Y') if @blog_post.published_at %></p>
            <p class="text-xl text-gray-300"><%= @blog_post.summary %></p>
          </div>
        </div>
        <div class="w-full md:w-1/2 sm:w-1/4">
          <div class="block">
            <%= image_tag @blog_post.cover_image, class: "object-cover rounded-lg max-h-64 sm:max-h-96 w-full h-full" if @blog_post.cover_image.present? %>
          </div>
        </div>
      </div>
      <div class="prose max-w-4xl sm:prose-sm md:prose-sm lg:prose-md xl:prose-lg text-white">
        <%= @blog_post.content %>
      </div>
    </div>
  </div>
</section>

app/views/home/contact.html.erb
<body class="bg-black text-white">
  <div class="container mx-auto px-4 py-12 relative z-10">
    <h1 class="text-4xl font-bold text-center mb-8">Ryan Richardson</h1>
    <p class="text-center mb-12">A highly-motivated web developer with broad experience, seeking a new challenge.</p>

    <div class="bg-gray-800 bg-opacity-80 p-6 rounded-md mb-8">
      <h2 class="text-2xl font-semibold mb-4">Contact</h2>
      <p>Email: <a href="mailto:rrichardson610@gmail.com" class="text-blue-400">rrichardson610@gmail.com</a></p>
      <p>GitHub: <a href="https://github.com/westnorthern" class="text-blue-400" target="_blank">https://github.com/westnorthern</a></p>
      <p>Web: <a href="https://ryanrichardson.space" class="text-blue-400" target="_blank">https://ryanrichardson.space</a></p>
      <p>LinkedIn: <a href="https://www.linkedin.com/in/ryan-richardson262/" class="text-blue-400" target="_blank">www.linkedin.com/in/ryan-richardson262/</a></p>
    </div>

    <div class="bg-gray-800 bg-opacity-80 p-6 rounded-md mb-8">
      <h2 class="text-2xl font-semibold mb-4">Education</h2>
      <p>Defense Language Institute, April 2006 - June 2007</p>
      <p>Mandarin, Chinese 3/3/3+</p>
      <p>New York Code + Design Academy</p>
      <p>Harvard CS50</p>
      <p>Stanford Supervised Machine Learning</p>
    </div>

    <div class="bg-gray-800 bg-opacity-80 p-6 rounded-md mb-8">
      <h2 class="text-2xl font-semibold mb-4">Professional Experience</h2>
      <!-- Mountain Measurement -->
      <div class="mb-6">
        <h3 class="text-xl font-bold">Mountain Measurement</h3>
        <p class="italic">Senior Software Engineer, March 2023 - July 2023</p>
        <ul class="list-disc list-inside">
          <li>Revitalized and optimized a legacy Rails codebase, introducing every new feature required for the company’s newest product.</li>
          <li>Created several new data visualizations for test psychometric data using R, TypeScript, and Chart.js</li>
          <li>Implemented and streamlined continuous deployment pipelines using Gitlab Auto DevOps and Capistrano, reducing deployment time by 70% and enhancing feature rollout efficiency.</li>
          <li>Introduced a suite of tests to a completely untested system using TestBench and Selenium</li>
        </ul>
      </div>
      <!-- LiveView Technologies -->
      <div class="mb-6">
        <h3 class="text-xl font-bold">LiveView Technologies</h3>
        <p class="italic">Senior Software Engineer, 2022 - 2023</p>
        <ul class="list-disc list-inside">
          <li>Led the design and implementation of event-driven microservices using the Eventide Project, facilitating the sharing of data between business domains, completely eliminating manual data entry in the accounting, fulfillment, support, and IT departments.</li>
          <li>Developed and enhanced CI/CD pipelines, supporting rapid scaling of operations.</li>
        </ul>
      </div>
      <!-- MX Technologies -->
      <div class="mb-6">
        <h3 class="text-xl font-bold">MX Technologies</h3>
        <p class="italic">Software Engineer, 2019 - 2022</p>
        <ul class="list-disc list-inside">
          <li>Engineered Ruby on Rails, Sinatra, JavaScript and Google Apps Script to build a large suite of custom tools, enhancing the productivity of the customer support department.</li>
          <li>Designed and managed over 50 Domo cards and Kibana dashboards that significantly enhanced business analytics capabilities.</li>
        </ul>
      </div>
      <!-- Ascend Software -->
      <div class="mb-6">
        <h3 class="text-xl font-bold">Ascend Software</h3>
        <p class="italic">Software Engineer, 2018 - 2019</p>
        <ul class="list-disc list-inside">
          <li>Developed and executed complex SQL queries to identify and resolve software bugs and to update database entries, ensuring data integrity and accuracy.</li>
          <li>Modernized and transitioned legacy VisualBasic applications to C#/.NET platforms, increasing performance and scalability.</li>
          <li>Collaborated closely with clients to develop tailored software solutions, enhancing user satisfaction and engagement.</li>
        </ul>
      </div>
      <!-- Solitude Mountain Resort -->
      <div class="mb-6">
        <h3 class="text-xl font-bold">Solitude Mountain Resort</h3>
        <p class="italic">Ski Patrol / Avalanche Mitigation , 2014 - 2017</p>
        <ul class="list-disc list-inside">
          <li>Collecting snowfall data and blasting snow with explosives as a member of the avalanche mitigation team.</li>
          <li>Provided emergency medical care and rescue services to mountain guests, backcountry skiers, and hikers alike as a member of Wasatch Backcountry Rescue.</li>
        </ul>
      </div>
      <!-- US Army -->
      <div class="mb-6">
        <h3 class="text-xl font-bold">US Army</h3>
        <p class="italic">Cryptologic Linguist, 2005 - 2010</p>
        <ul class="list-disc list-inside">
          <li>Demonstrated fluency in Mandarin Chinese through successful completion of the Defense Language Institute’s intensive language program.</li>
          <li>Applied linguistic skills to decode and translate complex communications in real-time.</li>
          <li>Fostered a collaborative team environment, promoting efficiency and cohesion during high-pressure missions.</li>
        </ul>
      </div>
    </div>

    <div class="bg-gray-800 bg-opacity-80 p-6 rounded-md mb-8">
      <h2 class="text-2xl font-semibold mb-4">Languages</h2>
      <p>Ruby; JavaScript; C# + .NET Core; HTML + CSS; SQL; Some experience in R, Golang, and Python.</p>
    </div>

    <div class="bg-gray-800 bg-opacity-80 p-6 rounded-md mb-8">
      <h2 class="text-2xl font-semibold mb-4">Technologies</h2>
      <p>Ruby on Rails; ASP.NET MVC; React Native; Eventide; Docker; Linux; NGINX; Apache; Git; Unity; Tailwind;</p>
    </div>

    <div class="bg-gray-800 bg-opacity-80 p-6 rounded-md">
      <h2 class="text-2xl font-semibold mb-4">Projects</h2>
      <!-- Curst -->
      <div class="mb-4">
        <h3 class="text-xl font-bold">Curst</h3>
        <p class="italic">Role: Lead Developer, Co-Creator, and Maintainer</p>
        <p>Description: Developed and maintained Curst, an open-source web application designed for discussing and trading spooky objects. Utilized React for the front-end and Ruby on Rails for the back-end.</p>
      </div>
      <!-- Tulipmania -->
      <div class="mb-4">
        <h3 class="text-xl font-bold">Tulipmania</h3>
        <p class="italic">Role: Lead Developer and Co-Creator</p>
        <p>Description: Led the development of Tulipmania, a video game set during the Dutch Golden Age. Collaborated with Kara Van de Graaf, a poet and professor at UVU, focusing on creating a new course on video game narrative. Built the project using Unity.</p>
      </div>
    </div>
  </div>
</body>

app/views/home/index.html.erb
<section class="relative bg-black">
  <div class="absolute inset-0 overflow-hidden z-0">
    <div class="absolute top-0 left-0 w-64 h-64 bg-gradient-to-br from-green-400 to-blue-500 opacity-50 blur-xl"></div>
    <div class="absolute top-1/2 left-1/3 w-96 h-96 bg-gradient-to-r from-yellow-400 to-red-500 opacity-50 blur-3xl"></div>
    <div class="absolute bottom-0 right-0 w-72 h-72 bg-gradient-to-tl from-purple-400 to-pink-500 opacity-50 blur-2xl"></div>
  </div>
  <div class="relative z-10 text-white pt-12 pr-0 pb-14 pl-0 bg-black bg-opacity-80">
    <div class="w-full pt-4 pr-5 pb-6 pl-5 mt-0 mr-auto mb-0 ml-auto space-y-5 sm:py-8 md:py-12 sm:space-y-8 md:space-y-16 max-w-7xl">
      <% @blog_posts.first(1).each do |blog_post| %>
        <a href="<%= blog_post_path(blog_post) %>" class="block">
          <div class="flex flex-col items-center sm:px-5 md:flex-row">
            <div class="flex flex-col items-start justify-center w-full h-full pt-6 pr-0 pb-6 pl-0 mb-6 md:mb-0 md:w-1/2">
              <div class="flex flex-col items-start justify-center h-full space-y-3 transform md:pr-10 lg:pr-16 md:space-y-5">
                <h2 class="text-4xl font-bold leading-none lg:text-5xl xl:text-6xl"><%= blog_post.title %></h2>
                <p class="text-sm text-gray-300"><%= truncate(blog_post.summary, length: 150) %></p>
                <div class="pt-2 pr-0 pb-0 pl-0">
                  <p class="inline text-sm font-medium mt-0 mr-1 mb-0 ml-1">· <%= blog_post.published_at.strftime('%d %b %Y') %> ·</p>
                </div>
              </div>
            </div>
            <div class="w-full md:w-1/2">
              <div class="block">
                <%= image_tag blog_post.cover_image, class: "object-cover rounded-lg max-h-64 sm:max-h-96 w-full h-full" if blog_post.cover_image.present? %>
              </div>
            </div>
          </div>
        </a>
      <% end %>
      <div class="grid grid-cols-12 sm:px-5 gap-x-8 gap-y-16">
        <% @blog_posts.drop(1).each do |blog_post| %>
          <a href="<%= blog_post_path(blog_post) %>" class="block col-span-12 sm:col-span-6 xl:col-span-4">
            <div class="flex flex-col items-start space-y-3">
              <%= image_tag blog_post.cover_image, class: "object-cover w-full mb-2 overflow-hidden rounded-lg shadow-sm max-h-56", alt: "Cover Image" if blog_post.cover_image.present? %>
              <h2 class="text-lg font-bold sm:text-xl md:text-2xl"><%= blog_post.title %></h2>
              <p class="text-sm text-gray-300"><%= truncate(blog_post.summary, length: 150) %></p>
              <div class="pt-2 pr-0 pb-0 pl-0">
                <p class="inline text-xs font-medium mt-0 mr-1 mb-0 ml-1">· <%= blog_post.published_at.strftime('%d %b %Y') if blog_post.published? %> ·</p>
              </div>
            </div>
          </a>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cromp</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= favicon_link_tag 'ycromp-fav.png' %>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="turbo-visit-control" content="reload">
  <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag "actiontext", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.17.1/themes/prism-okaidia.min.css" rel="stylesheet" />
  <link href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.17.1/plugins/line-numbers/prism-line-numbers.min.css" rel="stylesheet" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.17.1/components/prism-core.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.17.1/plugins/autoloader/prism-autoloader.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.17.1/plugins/line-numbers/prism-line-numbers.min.js"></script>
  <%= javascript_importmap_tags %>

    <!-- Google tag (gtag.js) -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-EL4LB257TD"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'G-EL4LB257TD');
  </script>
</head>
<body class="bg-black text-gray-900">
  <div class="flex flex-col md:flex-row">
    <!-- Sidebar Left -->
    <div class="w-full md:w-64 bg-black text-white flex flex-col items-center justify-center md:fixed md:inset-y-0 md:left-0">
      <div class="flex-shrink-0 px-8 pt-2 pb-4 flex items-center">
        <a href="<%= root_path %>">
          <img src="<%= asset_path('ycromp-cactus.png') %>" alt="Logo" class="w-full object-contain fade-sides">
        </a>
      </div>
      <nav class="mt-10 flex-1">
        <%#= link_to 'hmu', contact_path, class: 'block text-3xl py-2.5 px-4 rounded transition duration-200 hover:bg-gray-700 hover:text-white' %>
        <%#= link_to 'blog', root_path, class: 'block text-3xl py-2.5 px-4 rounded transition duration-200 hover:bg-gray-700 hover:text-white' %>
      </nav>
    </div>

    <!-- Main Content -->
    <div class="flex-1 p-6 bg-black text-white md:ml-64 md:mr-64" data-controller="trix-mark">
      <div data-trix-mark-target="source">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <%= yield %>
      </div>
    </div>

    <!-- Sidebar Right -->
    <div class="w-full md:w-64 bg-black text-white flex flex-col xl-custom:flex items-center justify-center space-y-10 md:fixed md:inset-y-0 md:right-0 hidden">
      <%= link_to 'https://www.linkedin.com/in/ryan-richardson262/', target: '_blank', class: 'text-white hover:text-gray-400' do %>
        <i class="fab fa-linkedin fa-3x"></i>
      <% end %>
      <%= link_to 'https://github.com/westnorthern', target: '_blank', class: 'text-white hover:text-gray-400' do %>
        <i class="fab fa-github fa-3x"></i>
      <% end %>
      <% if user_signed_in? %>
        <%= link_to "new post", new_blog_post_path, class: "inline-block bg-gradient-to-r from-green-400 to-blue-500 text-white font-bold py-2 px-4 rounded-md hover:from-green-500 hover:to-blue-600 transition duration-300" %>
        <%= button_to "logout", destroy_user_session_path, method: :delete, class: "inline-block bg-gradient-to-r from-green-400 to-blue-500 text-white font-bold py-2 px-4 rounded-md hover:from-green-500 hover:to-blue-600 transition duration-300" %>
      <% end %>
    </div>
  </div>
</body>
</html>